### ISSUE TITLE
Future of KOTORAutoMod

### ISSUE THREAD

**Issue by th3w1zard1** [woodske/KotorAutoMod#3]
I am the creator and maintainer of KOTORModSync.

It seems we are both coincidentally using .NET 6.0. Have you any interest in implementing some parts of KotorAutoMod into the project? For example the UI you have setup is sleek and would do it justice

**Comment by woodske** [comment]
Thanks for the offer. Unfortunately, I'm working on another project and don't have time, but I will let you know if that changes.
